// Instagram account random https://www.instagram.com/lahormonica.es/
// El reto de JS es el siguiente:

// En instagram, sacar un listado de las personas que yo sigo y a mi no me siguen.
const followers = [
  "angeneriis",
  "josecarlos_mbad",
  "tamsmile84",
  "abriendo.boca",
  "cftrading23",
  "espacovivax",
  "thalente_ngema",
  "ramongascoaparicio",
  "punto_.y_.coma",
  "girl_venture",
  "casamacareno",
  "augustomarcelocheves",
  "ellugardemartina",
  "pumukiylaura",
  "bocaitomadrid",
  "karenavidaconsciente",
  "surreyfoodies",
  "electronicspain",
  "trabajarmadrid",
  "brainbrewdiaries",
  "ctmpgonzalez",
  "cristobalmendez18",
  "dentalcorchuelo",
  "edu_alba89",
  "logofaster",
  "mukkittus",
  "evers_ann_",
  "stephenlieuu",
  "nayolito22",
  "agalvezcdesign",
  "anais_lookshoponline",
  "aplauso.es",
  "murderpink",
  "marinacendon",
  "lmprodutospet",
  "hctor7",
  "patriiiiiiii.q",
  "_jade__jones",
  "henarmi",
  "free_wanderluster",
  "nerve10mentalhealth",
  "vivi.frias85",
  "thesilverlagoonboutique",
  "real_workers_pro",
  "animal_limit",
  "casabenigna",
  "photo.nicc",
  "instagain_io",
  "fashionlover2225",
  "criscavero86",
  "schwarzerporsche",
  "worldscanner1",
  "losangeles77shop",
  "rubenrube",
  "borjas_carolina2016",
  "karlagmg_",
  "karlasz86",
  "capuky",
  "natty_mimundo_lo_contiene_todo",
];

const follows = [
  "angeneriis",
  "karlasz86",
  "capuky",
  "karlagmg_",
  "marinacendon",
  "abriendo.boca",
  "vivi.frias85",
  "leyre.j",
  "surreyfoodies",
  "punto_.y_.coma ",
  "casamacareno",
  "elsundance  ",
  "mikedemusic ",
  "_jade__jones",
  "casabenigna ",
  "la.joyademexico",
  "activate__contati",
  "am_jececa",
  "schwarzerporsche",
  "meetupes",
  "senoritaguerrero2",
  "dentalcorchuelo",
  "ramongascoaparicio  ",
  "thalente_ngema ",
  "malamudnadav",
  "pumukiylaura",
  "thegoodlife911 ",
  "animal_limit",
  "tamaranavarro7949",
  "easycauliflowerhour ",
  "karenavidaconsciente",
  "_sebastiantimis",
  "_flying_in_the_sea  ",
  "fashionlover2225",
  "vintagemoodbcn ",
  "eventodivertidospain",
  "castingfortwo",
  "detallesconamor.gastrolounge",
  "tentacionesdeplata  ",
  "walterman_marketing ",
  "worldscanner1",
  "gio.giramondo",
  "ollieharrison_1",
  "mon_ikkaa",
  "cftrading23 ",
  "whis_magazine",
  "im_luisacastillo",
  "joceliu",
  "jasalgastronomy",
  "talk.design.to.me",
  "beautyismylife02",
  "nagema",
  "partanenprocess",
  "atrevindicativa",
  "uxdesignjobs",
  "augustomarcelocheves",
  "nerve10mentalhealth ",
  "thestyleclubla ",
  "brainbrewdiaries",
  "stephenlieuu",
  "coeur_the_dentist",
  "hellogiggles",
  "espacovivax ",
  "fardinsamdai0111420 ",
  "barbaraannmadrid",
  "girl_venture",
  "losangeles77shop",
  "irenegrande.pmu",
  "bsmntprty",
  "lapikowa777 ",
  "lacarlotamadrid",
  "elimparcialmadrid",
  "acusticosnacionales ",
  "forever21eu ",
  "bocaitomadrid",
  "photo.nicc  ",
  "thesilverlagoonboutique",
  "tabilioficial",
  "tucocinatv  ",
  "caro.dibuja ",
  "dialogosdeunagorda  ",
  "uglykindness",
  "vanesagarand",
  "ellugardemartina",
  "diariodeunachicafeliz",
  "studiograndpere",
  "real_workers_pro",
  "july_custom ",
  "pasionesargentinas  ",
  "illustrated.doris",
  "melaniab_ilustracion",
  "murderpink  ",
  "tapean2",
  "jenniferlongmore",
  "birchbox",
  "nobasicbombshell",
  "radicalgirlgang",
  "dondecomemosahora",
  "the.wing",
  "banannabones",
  "meetup",
  "recipesforselflove  ",
  "humana_secondhand_es",
  "le_petit_patito",
  "birchboxes  ",
  "technologyreview",
  "muymucho",
  "psychedelalune ",
  "almejeiter  ",
  "marta.piedra",
  "clinique_es ",
  "squaresayings",
  "_alexismoyano",
  "sofiaweidner",
  "stacieswift ",
  "agustinaguerrero",
  "theblurtfoundation  ",
  "cityconf",
  "hastaelco__ ",
  "picame",
  "winkmagazine",
  "thehappynewspaper",
  "createcultivate",
  "melodieperrault",
  "spiritualist_within ",
  "britandco",
  "gooseberry  ",
  "artleove",
  "lianafinck  ",
  "elmundotoday",
  "popcultureinpictures_",
  "nastygal",
  "streetartglobe ",
  "positivelypresent",
  "modernadepueblo",
  "witchyfeelings_",
  "80svintagecomics",
  "voguespain  ",
  "lavecinarubia",
  "designershumor ",
  "forever21",
  "unwomen",
  "freeda_es",
  "selfcareisforeveryone",
  "theawkwardyeti ",
  "girlboss",
  "the.pinklemonade",
  "el_pais",
  "feminist",
  "sarcasm_only",
  "cabronazi",
  "netflixes",
  "theellenshow",
];

function followsThatDontFollowBack(list) {
  let noFollowList = [];
  for (let index = 0; index < list.length; index++) {
    //59 followers
    const follow = list[index];

    if (!followers.includes(follow)) {
      //153 follows

      noFollowList.push(follow);
    }
  }
  return noFollowList; // result 127
}
console.log(followsThatDontFollowBack(follows));
